### ISSUE TITLE
Sign In With Slack Oauth is now using OpenID Connect standard

### ISSUE THREAD

**Issue by kwent** [ginjo/omniauth-slack#21]
Not really an issue, but i wanted to make sure people are aware:

It's based on the OpenID Connect standard, built on top of OAuth 2.0.

New flow: https://api.slack.com/authentication/sign-in-with-slack
Legacy flow: https://api.slack.com/legacy/sign-in-with-slack

I believe https://github.com/m0n9oose/omniauth_openid_connect can support `Sign In with Slack` new Oauth flow. (Untested)

**Comment by fayeroske** [comment]
I'm also trying to sort this one out, in the throes of our Granular Scopes / OAuth 2.0 v2 migration.  

It looks like [this](https://github.com/nov/openid_connect) is the certified implementation package. Though it'd be cool if we didn't have to add another gem to our solution for it.

It sounds like this actually might be an issue.  Slack Support informed us that `identity.*` scopes are deprecated, and any future changes to our Slack App will be rejected if we don't upgrade to use the [OpenID scopes](https://api.slack.com/authentication/sign-in-with-slack#migrate).

**Comment by kwent** [comment]
https://github.com/amkisko/omniauth-slack-openid.rb does it well
