### ISSUE TITLE
Getting a bad redirect_uri error. Seems to be due to passing the redirect_uri with the code parameter to the get_token method

### ISSUE THREAD

**Issue by miguelperez** [ginjo/omniauth-slack#3]
Hi, thanks for this refactor!!! 

I was getting the following error:

```
(sign_in_with_slack) Authentication failure! invalid_credentials: OAuth2::Error, bad_redirect_uri:
{"ok":false,"error":"bad_redirect_uri"}
```
Using the `gem 'httplog'` I was able to see that the post to get the token does indeed add the redirect_uri param but it does so using the uri and the params received from slack with the code and state attributes.

I noticed in the original repo the method `callback_url` is overwritten removing `+ query_string` part. [Original code Here](https://github.com/kmrshntr/omniauth-slack/blob/master/lib/omniauth/strategies/slack.rb#L103)

But in this one that one is commented. [Modified one here](https://github.com/ginjo/omniauth-slack/blob/master/lib/omniauth/strategies/slack.rb#L181)

I uncommented it again and it worked for me. Is there any reason I am not seeing why that method should be commented?

Here is an screenshot of this working on my local environment with three methods being requested: users.info, user.identity and team.info:

![screen shot 2018-08-10 at 7 23 17 am](https://user-images.githubusercontent.com/141042/43958058-af6e9858-9c6f-11e8-9b03-1523b6aa94cc.png)

Do you have a working example showcasing:

1. sign in with slack to get basic information about the user
2. sign in to other scopes to enhance user exeperience

Thanks,

**Comment by miguelperez** [comment]
> Is there a consistent way to reproduce this issue?
This is my setup:

```ruby
OmniAuth.config.logger = Rails.logger if Rails.env.development?
OmniAuth.config.full_host = "#{Rails.application.credentials[Rails.env.to_sym][:app_domain]}"

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :slack, 
    Rails.application.credentials[Rails.env.to_sym][:slack_client_id], 
    Rails.application.credentials[Rails.env.to_sym][:slack_client_secret], 
    scope: 'identity.basic,identity.email',
    name: :sign_in_with_slack,
    redirect_uri: "http://#{Rails.application.credentials[Rails.env.to_sym][:app_domain]}/auth/sign_in_with_slack/callback"

  provider :slack, 
    Rails.application.credentials[Rails.env.to_sym][:slack_client_id], 
    Rails.application.credentials[Rails.env.to_sym][:slack_client_secret], 
    scope: 'channels:history,channels:read,groups:history,groups:read',
    redirect_uri: "http://#{Rails.application.credentials[Rails.env.to_sym][:app_domain]}/auth/slack/callback"
end
```

and this is how I am calling it:

```ruby
<%= link_to('authenticate with slack', '/auth/sign_in_with_slack')%>
```

> Is this issue only when calling /api/oauth.access or also when calling other Slack api methods?

This happens using the normal flow, it fails when it wants to exchange the code for the access token in the `get_token` method.

> Is this issue specific to omniauth-slack, or is it know to affect other omniauth-oauth2 strategies?
I think I saw a similar issue with the omniauth-google gem. But I am not totally sure.

**Comment by miguelperez** [comment]
I think you can close this issue then after you publish your change fix.

**Comment by ginjo** [comment]
Ok, thanks for the info. I've published the fix to the master branch, and I'll put up some working examples when I return from a couple weeks of traveling.

**Comment by ginjo** [comment]
Hi @miguelperez , I have released this fork as ginjo-omniauth-slack-2.4.0.gem on rubygems.org. Check out the readme and changelog for more info. I'm also working on an example app that demonstrates usage. I'll post back when I get something uploaded.

I'm closing this issue for now, but please feel free to continue conversation on this topic.

**Comment by chrismanderson** [comment]
Thanks for this fork! Setting up an "Add to Slack" button now, but it's honestly been incredible confusing, as Oauth and I do not get along well. Any chance of seeing that example app you mentioned sooner rather than later?

**Comment by ginjo** [comment]
Hi @chrismanderson, I definitely feel your pain... I've been immersed in OAuth2 and OmniAuth for several months now, and I still get tripped up. Stick with it though, and the puzzle will start to make more sense. 

I hope to publish my example app soon, but I need to do some cleanup first. I don't want the app to make the confusion any worse 😆.

**Comment by chrismanderson** [comment]
Sounds good! 

For what it's worth, the challenge I face in integrating this library/OmniAuth in general is that it is difficult to determine what pieces of the auth flow I need to implement, and what pieces are provided from the gem. (E.g. routes, controllers, methods, in controllers, etc.) Ideally, the readme too would illustrate what you need to do after the steps of inserting the middleware. That's where I hit the speed bump, so in both readme and sample app, that's where I'd love love love to see more information.

**Comment by ginjo** [comment]
Thanks for the feedback. I think you're spot-on with why this gets confusing. I'm working on a basic rundown of the Slack OAuth cycle and how the gem fits in. I'll post back when I have something relatively readable.

**Comment by ginjo** [comment]
Ok, here's a little something that might help, or it might confuse the issue even more, hopefully the former. This document contains some explanation plus a bare-bones example that should work for ginjo-omniauth-slack as well as kmrshntr's omniauth-slack. I'd like to incorporate this into the general readme, so let me know if you find it helpful or not.

https://gist.github.com/ginjo/5fe43b4af8dd5b56725232548cda5d75

Thanks

**Comment by chrismanderson** [comment]
This is a great start. I'd like to see a Rails bare-bones example as well. And, some more detail around Step 3, which from what I can tell, in a Rails app, would need a route and controller defined - just to make that explicit. But overall this is helpful for sure.

**Comment by ginjo** [comment]
Cool. I added a Rails example to the gist. It shows the route and controller/action you mentioned. I also added Gemfile entries for each of the  examples.
