### ISSUE TITLE
Load Error: Could not find matching strategy for :slack. You may need to install an additional gem (such as omniauth-slack).

### ISSUE THREAD

**Issue by pablobfonseca** [ginjo/omniauth-slack#4]
Hi,
I'm getting a `LoadError` when trying to start rails server, am I missing something? I've added `gem 'ginjo-omniauth-slack', git: 'https://github.com/ginjo/omniauth-slack'` to the Gemfile.

Thanks in advance!

**Comment by pablobfonseca** [comment]
Never mind, I've figure the problem, I had to require 'omniauth-slack' on `config/initializers/omniauth.rb`, closing issue.

**Comment by minhajuddin** [comment]
Another way of doing this is by using the following in your Gemfile: 

```ruby
gem 'ginjo-omniauth-slack', require: 'omniauth-slack'
```

**Comment by espen** [comment]
Perhaps use that as the example in the readme or at least mention it?

**Comment by minhajuddin** [comment]
I've added a PR to change that in the README #5 Hopefully it will get merged soon :)

**Comment by pablobfonseca** [comment]
Thank you guys!

**Comment by ginjo** [comment]
Thanks for pointing this out... I'll merge the PR for the readme updates.
